name: Build and Push Docker Image

on:
    workflow_dispatch:

env:
    IMAGE_NAME: mycoreapp
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            image_tag: ${{ steps.tag.outputs.image_tag }}

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up .NET 8 SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'
            
            - name: Build
              run: dotnet build --configuration Release

            - name: Publish
              run: dotnet publish -c Release -o out

            - name: Set image tag
              id: tag
              run: echo " image_tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

            - name: Build Docker image
              run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:${{ steps.tag.outputs.image_tag }} .
              

    approve-and-push:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: production
            url: https://hub.docker.com/repository/docker/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        steps:
            - name: Log in to Docker
              run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

            - name: Push Docker image
              run: docker push $DOCKER_USERNAME/$IMAGE_NAME:${{ needs.build.outputs.image_tag }}